{
 "title": "Web",
 "tags": [ "linux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"192.168.255.2:9100\",job=\"web\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"192.168.255.2:9100\",job=\"web\"}[30s])))) * 100) / count(count(node_cpu_seconds_total{instance=\"192.168.255.2:9100\",job=\"web\"}) by (cpu))",
     "legendFormat": "qwe"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"192.168.255.2:9100\",job=\"web\"} - node_boot_time_seconds{instance=\"192.168.255.2:9100\",job=\"web\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.255.2:9100\",job=\"web\"}"
    }
   ]
  },
  {
   "title": "Node availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"192.168.255.2:9100\",job=\"web\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"192.168.255.2:9100\",job=\"web\"} - node_memory_MemFree_bytes{instance=\"192.168.255.2:9100\",job=\"web\"}) / (node_memory_MemTotal_bytes{instance=\"192.168.255.2:9100\",job=\"web\"} )) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.255.2:9100\",job=\"web\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"192.168.255.2:9100\",job=\"web\",device!~'rootfs'})"
    }
   ]
  }
 ]
}